<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="4" total="7" passed="0" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-11-30T13:25:30 IST" name="Suite" finished-at="2022-11-30T13:25:37 IST" duration-ms="6779">
    <groups>
    </groups>
    <test started-at="2022-11-30T13:25:30 IST" name="Test" finished-at="2022-11-30T13:25:37 IST" duration-ms="6779">
      <class name="tests.rest.TC001_CreateIncident">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:tests.rest.TC001_CreateIncident@514646ef]" started-at="2022-11-30T13:25:29 IST" name="beforeSuite" finished-at="2022-11-30T13:25:30 IST" duration-ms="800" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="setValues()[pri:0, instance:tests.rest.TC001_CreateIncident@514646ef]" started-at="2022-11-30T13:25:30 IST" name="setValues" finished-at="2022-11-30T13:25:30 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setValues -->
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:tests.rest.TC001_CreateIncident@514646ef]" started-at="2022-11-30T13:25:30 IST" name="beforeClass" finished-at="2022-11-30T13:25:30 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:tests.rest.TC001_CreateIncident@514646ef]" started-at="2022-11-30T13:25:30 IST" name="beforeMethod" finished-at="2022-11-30T13:25:30 IST" duration-ms="8" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="createIncident(java.io.File)[pri:0, instance:tests.rest.TC001_CreateIncident@514646ef]" started-at="2022-11-30T13:25:30 IST" name="createIncident" data-provider="fetchData" finished-at="2022-11-30T13:25:33 IST" duration-ms="3330" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[.\data\TC001.JSON]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
at lib.utils.HTMLReporter.reportRequest(HTMLReporter.java:102)
at lib.rest.RESTAssuredBase.verifyContentType(RESTAssuredBase.java:206)
at tests.rest.TC001_CreateIncident.createIncident(TC001_CreateIncident.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createIncident -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:tests.rest.TC001_CreateIncident@514646ef]" started-at="2022-11-30T13:25:33 IST" name="afterMethod" finished-at="2022-11-30T13:25:33 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:tests.rest.TC001_CreateIncident@514646ef]" started-at="2022-11-30T13:25:37 IST" name="afterSuite" finished-at="2022-11-30T13:25:37 IST" duration-ms="287" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- tests.rest.TC001_CreateIncident -->
      <class name="tests.rest.TC011_PutIncident2">
        <test-method is-config="true" signature="setValues()[pri:0, instance:tests.rest.TC011_PutIncident2@548a24a]" started-at="2022-11-30T13:25:30 IST" name="setValues" finished-at="2022-11-30T13:25:30 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setValues -->
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:tests.rest.TC011_PutIncident2@548a24a]" started-at="2022-11-30T13:25:33 IST" name="beforeClass" finished-at="2022-11-30T13:25:33 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:tests.rest.TC011_PutIncident2@548a24a]" started-at="2022-11-30T13:25:33 IST" name="beforeMethod" finished-at="2022-11-30T13:25:33 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="putIncident(java.io.File)[pri:0, instance:tests.rest.TC011_PutIncident2@548a24a]" started-at="2022-11-30T13:25:33 IST" name="putIncident" data-provider="fetchData" finished-at="2022-11-30T13:25:35 IST" depends-on-methods="tests.rest.TC001_CreateIncident.createIncident" duration-ms="1716" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[.\data\TC2.JSON]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
at lib.utils.HTMLReporter.reportRequest(HTMLReporter.java:102)
at lib.rest.RESTAssuredBase.verifyContentType(RESTAssuredBase.java:206)
at tests.rest.TC011_PutIncident2.putIncident(TC011_PutIncident2.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- putIncident -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:tests.rest.TC011_PutIncident2@548a24a]" started-at="2022-11-30T13:25:35 IST" name="afterMethod" finished-at="2022-11-30T13:25:35 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- tests.rest.TC011_PutIncident2 -->
      <class name="tests.rest.TC011_delete3">
        <test-method is-config="true" signature="setValues()[pri:0, instance:tests.rest.TC011_delete3@433defed]" started-at="2022-11-30T13:25:30 IST" name="setValues" finished-at="2022-11-30T13:25:30 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setValues -->
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:tests.rest.TC011_delete3@433defed]" started-at="2022-11-30T13:25:35 IST" name="beforeClass" finished-at="2022-11-30T13:25:35 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:tests.rest.TC011_delete3@433defed]" started-at="2022-11-30T13:25:35 IST" name="beforeMethod" finished-at="2022-11-30T13:25:35 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="deleteIncident()[pri:0, instance:tests.rest.TC011_delete3@433defed]" started-at="2022-11-30T13:25:35 IST" name="deleteIncident" finished-at="2022-11-30T13:25:37 IST" depends-on-methods="tests.rest.TC011_PutIncident2.putIncident" duration-ms="1640" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
at lib.utils.HTMLReporter.reportRequest(HTMLReporter.java:102)
at lib.rest.RESTAssuredBase.verifyResponseCode(RESTAssuredBase.java:214)
at tests.rest.TC011_delete3.deleteIncident(TC011_delete3.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteIncident -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:tests.rest.TC011_delete3@433defed]" started-at="2022-11-30T13:25:37 IST" name="afterMethod" finished-at="2022-11-30T13:25:37 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- tests.rest.TC011_delete3 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
